IF object_id(N'${RiyoDataDatabaseName}.dbo.D_RIYO_DATA_C1_${Sta}') IS NULL
BEGIN
  CREATE TABLE ${RiyoDataDatabaseName}.dbo.D_RIYO_DATA_C1_${Sta}
  (
    UPDATE_DATE datetime NOT NULL,
    基本ヘッダーデータ種別 binary(1),
    基本ヘッダー処理日時 binary(7) NOT NULL,
    基本ヘッダーコーナー binary(1) NOT NULL,
    基本ヘッダー号機 binary(1) NOT NULL,
    基本ヘッダーシーケンスNo binary(4) NOT NULL,
    基本ヘッダーバージョン binary(1),
    基本ヘッダー駅コード binary(2) NOT NULL,
    通過方向 binary(1),
    ラッチ形態 binary(1),
    判定結果 binary(2),
    発着情報乗車券発駅 binary(2),
    発着情報乗車券着駅 binary(2),
    発着情報特急券発駅 binary(2),
    発着情報特急券着駅 binary(2),
    発着情報のぞみ区間発駅 binary(2),
    発着情報のぞみ区間着駅 binary(2),
    発着情報グリーン区間発駅 binary(2),
    発着情報グリーン区間着駅 binary(2),
    発着情報IC区間発駅 binary(2),
    発着情報IC区間着駅 binary(2),
    発着情報フリー区間 binary(2),
    発着情報FREX区間発駅 binary(2),
    発着情報FREX区間着駅 binary(2),
    入場駅情報乗車券入場駅 binary(2),
    入場駅情報乗車券コーナ binary(1),
    入場駅情報乗車券号機 binary(1),
    入場駅情報特急券入場駅 binary(2),
    入場日時情報乗車券月日時分 binary(4),
    入場日時情報特急券月日時分 binary(4),
    当駅迄券情報乗車券乗車駅 binary(2),
    当駅迄券情報乗車券コーナ binary(1),
    当駅迄券情報乗車券号機 binary(1),
    当駅迄券情報特急券乗車駅 binary(2),
    当駅から券情報乗車券着駅 binary(2),
    大小区分大人小児 binary(1),
    性別区分男性女性 binary(1),
    IC利用新幹線IC利用 binary(1),
    IC利用まで券IC利用 binary(1),
    IC利用から券IC利用 binary(1),
    指定券情報指定１指定区間 binary(4),
    指定券情報指定１列車番号 binary(3),
    指定券情報指定１号車番号 binary(1),
    指定券情報指定１席番 binary(2),
    指定券情報指定２指定区間 binary(4),
    指定券情報指定２列車番号 binary(3),
    指定券情報指定２号車番号 binary(1),
    指定券情報指定２席番 binary(2),
    指定券情報指定３指定区間 binary(4),
    指定券情報指定３列車番号 binary(3),
    指定券情報指定３号車番号 binary(1),
    指定券情報指定３席番 binary(2),
    不正判定対象区分ビット binary(1),
    不正判定ＮＧ項目 binary(1),
    投入枚数 binary(1),
    併用パターン種別 binary(1),
    券読取情報１枚目情報集計券種 binary(1),
    券読取情報１枚目情報乗車券区間 binary(4),
    券読取情報１枚目情報特急券区間 binary(4),
    券読取情報１枚目情報フリー区間 binary(2),
    券読取情報１枚目情報区数 binary(2),
    券読取情報１枚目情報入出場情報 binary(1),
    券読取情報１枚目情報ビット binary(2),
    券読取情報１枚目情報割引 binary(1),
    券読取情報１枚目情報EXIC割引 binary(1),
    券読取情報１枚目情報商品番号 binary(3),
    券読取情報１枚目情報発行会社 binary(2),
    券読取情報１枚目情報有効開始日 binary(4),
    券読取情報１枚目情報発行月日 binary(2),
    券読取情報１枚目情報号車番号 binary(1),
    券読取情報１枚目情報料金券区分 binary(1),
    券読取情報２枚目情報集計券種 binary(1),
    券読取情報２枚目情報乗車券区間 binary(4),
    券読取情報２枚目情報特急券区間 binary(4),
    券読取情報２枚目情報フリー区間 binary(2),
    券読取情報２枚目情報区数 binary(2),
    券読取情報２枚目情報入出場情報 binary(1),
    券読取情報２枚目情報ビット binary(2),
    券読取情報２枚目情報割引 binary(1),
    券読取情報２枚目情報EXIC割引 binary(1),
    券読取情報２枚目情報商品番号 binary(3),
    券読取情報２枚目情報発行会社 binary(2),
    券読取情報２枚目情報有効開始日 binary(4),
    券読取情報２枚目情報発行月日 binary(2),
    券読取情報２枚目情報号車番号 binary(1),
    券読取情報２枚目情報料金券区分 binary(1),
    券読取情報３枚目情報集計券種 binary(1),
    券読取情報３枚目情報乗車券区間 binary(4),
    券読取情報３枚目情報特急券区間 binary(4),
    券読取情報３枚目情報フリー区間 binary(2),
    券読取情報３枚目情報区数 binary(2),
    券読取情報３枚目情報入出場情報 binary(1),
    券読取情報３枚目情報ビット binary(2),
    券読取情報３枚目情報割引 binary(1),
    券読取情報３枚目情報EXIC割引 binary(1),
    券読取情報３枚目情報商品番号 binary(3),
    券読取情報３枚目情報発行会社 binary(2),
    券読取情報３枚目情報有効開始日 binary(4),
    券読取情報３枚目情報発行月日 binary(2),
    券読取情報３枚目情報号車番号 binary(1),
    券読取情報３枚目情報料金券区分 binary(1),
    券読取情報４枚目情報集計券種 binary(1),
    券読取情報４枚目情報乗車券区間 binary(4),
    券読取情報４枚目情報特急券区間 binary(4),
    券読取情報４枚目情報フリー区間 binary(2),
    券読取情報４枚目情報区数 binary(2),
    券読取情報４枚目情報入出場情報 binary(1),
    券読取情報４枚目情報ビット binary(2),
    券読取情報４枚目情報割引 binary(1),
    券読取情報４枚目情報EXIC割引 binary(1),
    券読取情報４枚目情報商品番号 binary(3),
    券読取情報４枚目情報発行会社 binary(2),
    券読取情報４枚目情報有効開始日 binary(4),
    券読取情報４枚目情報発行月日 binary(2),
    券読取情報４枚目情報号車番号 binary(1),
    券読取情報４枚目情報料金券区分 binary(1),
    ＩＤ番号 binary(5),
    ＳＦ引去り金額 binary(4),
    ＳＦ利用区間１・利用駅１ binary(2),
    ＳＦ利用区間１・利用駅２ binary(2),
    ＳＦ利用区間２・利用駅１ binary(2),
    ＳＦ利用区間２・利用駅２ binary(2),
    乗車始点駅 binary(2),
    券通しマスタ適用有無 binary(1),
    予備 binary(6),
    サム値 binary(2),
    判定ＮＧコード１ binary(2),
    判定ＮＧコード１該当券 binary(4),
    判定ＮＧコード２ binary(2),
    判定ＮＧコード２該当券 binary(4),
    判定ＮＧコード３ binary(2),
    判定ＮＧコード３該当券 binary(4),
    判定ＮＧコード４ binary(2),
    判定ＮＧコード４該当券 binary(4),
    判定ＮＧコード５ binary(2),
    判定ＮＧコード５該当券 binary(4),
    判定ＮＧコード６ binary(2),
    判定ＮＧコード６該当券 binary(4),
    判定ＮＧコード７ binary(2),
    判定ＮＧコード７該当券 binary(4),
    判定ＮＧコード８ binary(2),
    判定ＮＧコード８該当券 binary(4),
    券エンコード情報１枚目情報 binary(288),
    券エンコード情報２枚目情報 binary(288),
    券エンコード情報３枚目情報 binary(288),
    券エンコード情報４枚目情報 binary(288)
  );
  ALTER TABLE ${RiyoDataDatabaseName}.dbo.D_RIYO_DATA_C1_${Sta}
  ADD CONSTRAINT pk_D_RIYO_DATA_C1_${Sta} PRIMARY KEY (基本ヘッダー処理日時,基本ヘッダー駅コード,基本ヘッダーコーナー,基本ヘッダー号機,基本ヘッダーシーケンスNo);
  CREATE INDEX idx_D_RIYO_DATA_C1_${Sta} ON ${RiyoDataDatabaseName}.dbo.D_RIYO_DATA_C1_${Sta}(UPDATE_DATE);
END;

IF object_id(N'D_RIYO_DATA_C1_TEMP_${Sta}') IS NULL
BEGIN
  CREATE TABLE D_RIYO_DATA_C1_TEMP_${Sta}
  (
    基本ヘッダーデータ種別 binary(1),
    基本ヘッダー処理日時 binary(7) NOT NULL,
    基本ヘッダーコーナー binary(1) NOT NULL,
    基本ヘッダー号機 binary(1) NOT NULL,
    基本ヘッダーシーケンスNo binary(4) NOT NULL,
    基本ヘッダーバージョン binary(1),
    基本ヘッダー駅コード binary(2) NOT NULL,
    通過方向 binary(1),
    ラッチ形態 binary(1),
    判定結果 binary(2),
    発着情報乗車券発駅 binary(2),
    発着情報乗車券着駅 binary(2),
    発着情報特急券発駅 binary(2),
    発着情報特急券着駅 binary(2),
    発着情報のぞみ区間発駅 binary(2),
    発着情報のぞみ区間着駅 binary(2),
    発着情報グリーン区間発駅 binary(2),
    発着情報グリーン区間着駅 binary(2),
    発着情報IC区間発駅 binary(2),
    発着情報IC区間着駅 binary(2),
    発着情報フリー区間 binary(2),
    発着情報FREX区間発駅 binary(2),
    発着情報FREX区間着駅 binary(2),
    入場駅情報乗車券入場駅 binary(2),
    入場駅情報乗車券コーナ binary(1),
    入場駅情報乗車券号機 binary(1),
    入場駅情報特急券入場駅 binary(2),
    入場日時情報乗車券月日時分 binary(4),
    入場日時情報特急券月日時分 binary(4),
    当駅迄券情報乗車券乗車駅 binary(2),
    当駅迄券情報乗車券コーナ binary(1),
    当駅迄券情報乗車券号機 binary(1),
    当駅迄券情報特急券乗車駅 binary(2),
    当駅から券情報乗車券着駅 binary(2),
    大小区分大人小児 binary(1),
    性別区分男性女性 binary(1),
    IC利用新幹線IC利用 binary(1),
    IC利用まで券IC利用 binary(1),
    IC利用から券IC利用 binary(1),
    指定券情報指定１指定区間 binary(4),
    指定券情報指定１列車番号 binary(3),
    指定券情報指定１号車番号 binary(1),
    指定券情報指定１席番 binary(2),
    指定券情報指定２指定区間 binary(4),
    指定券情報指定２列車番号 binary(3),
    指定券情報指定２号車番号 binary(1),
    指定券情報指定２席番 binary(2),
    指定券情報指定３指定区間 binary(4),
    指定券情報指定３列車番号 binary(3),
    指定券情報指定３号車番号 binary(1),
    指定券情報指定３席番 binary(2),
    不正判定対象区分ビット binary(1),
    不正判定ＮＧ項目 binary(1),
    投入枚数 binary(1),
    併用パターン種別 binary(1),
    券読取情報１枚目情報集計券種 binary(1),
    券読取情報１枚目情報乗車券区間 binary(4),
    券読取情報１枚目情報特急券区間 binary(4),
    券読取情報１枚目情報フリー区間 binary(2),
    券読取情報１枚目情報区数 binary(2),
    券読取情報１枚目情報入出場情報 binary(1),
    券読取情報１枚目情報ビット binary(2),
    券読取情報１枚目情報割引 binary(1),
    券読取情報１枚目情報EXIC割引 binary(1),
    券読取情報１枚目情報商品番号 binary(3),
    券読取情報１枚目情報発行会社 binary(2),
    券読取情報１枚目情報有効開始日 binary(4),
    券読取情報１枚目情報発行月日 binary(2),
    券読取情報１枚目情報号車番号 binary(1),
    券読取情報１枚目情報料金券区分 binary(1),
    券読取情報２枚目情報集計券種 binary(1),
    券読取情報２枚目情報乗車券区間 binary(4),
    券読取情報２枚目情報特急券区間 binary(4),
    券読取情報２枚目情報フリー区間 binary(2),
    券読取情報２枚目情報区数 binary(2),
    券読取情報２枚目情報入出場情報 binary(1),
    券読取情報２枚目情報ビット binary(2),
    券読取情報２枚目情報割引 binary(1),
    券読取情報２枚目情報EXIC割引 binary(1),
    券読取情報２枚目情報商品番号 binary(3),
    券読取情報２枚目情報発行会社 binary(2),
    券読取情報２枚目情報有効開始日 binary(4),
    券読取情報２枚目情報発行月日 binary(2),
    券読取情報２枚目情報号車番号 binary(1),
    券読取情報２枚目情報料金券区分 binary(1),
    券読取情報３枚目情報集計券種 binary(1),
    券読取情報３枚目情報乗車券区間 binary(4),
    券読取情報３枚目情報特急券区間 binary(4),
    券読取情報３枚目情報フリー区間 binary(2),
    券読取情報３枚目情報区数 binary(2),
    券読取情報３枚目情報入出場情報 binary(1),
    券読取情報３枚目情報ビット binary(2),
    券読取情報３枚目情報割引 binary(1),
    券読取情報３枚目情報EXIC割引 binary(1),
    券読取情報３枚目情報商品番号 binary(3),
    券読取情報３枚目情報発行会社 binary(2),
    券読取情報３枚目情報有効開始日 binary(4),
    券読取情報３枚目情報発行月日 binary(2),
    券読取情報３枚目情報号車番号 binary(1),
    券読取情報３枚目情報料金券区分 binary(1),
    券読取情報４枚目情報集計券種 binary(1),
    券読取情報４枚目情報乗車券区間 binary(4),
    券読取情報４枚目情報特急券区間 binary(4),
    券読取情報４枚目情報フリー区間 binary(2),
    券読取情報４枚目情報区数 binary(2),
    券読取情報４枚目情報入出場情報 binary(1),
    券読取情報４枚目情報ビット binary(2),
    券読取情報４枚目情報割引 binary(1),
    券読取情報４枚目情報EXIC割引 binary(1),
    券読取情報４枚目情報商品番号 binary(3),
    券読取情報４枚目情報発行会社 binary(2),
    券読取情報４枚目情報有効開始日 binary(4),
    券読取情報４枚目情報発行月日 binary(2),
    券読取情報４枚目情報号車番号 binary(1),
    券読取情報４枚目情報料金券区分 binary(1),
    ＩＤ番号 binary(5),
    ＳＦ引去り金額 binary(4),
    ＳＦ利用区間１・利用駅１ binary(2),
    ＳＦ利用区間１・利用駅２ binary(2),
    ＳＦ利用区間２・利用駅１ binary(2),
    ＳＦ利用区間２・利用駅２ binary(2),
    乗車始点駅 binary(2),
    券通しマスタ適用有無 binary(1),
    予備 binary(6),
    サム値 binary(2),
    判定ＮＧコード１ binary(2),
    判定ＮＧコード１該当券 binary(4),
    判定ＮＧコード２ binary(2),
    判定ＮＧコード２該当券 binary(4),
    判定ＮＧコード３ binary(2),
    判定ＮＧコード３該当券 binary(4),
    判定ＮＧコード４ binary(2),
    判定ＮＧコード４該当券 binary(4),
    判定ＮＧコード５ binary(2),
    判定ＮＧコード５該当券 binary(4),
    判定ＮＧコード６ binary(2),
    判定ＮＧコード６該当券 binary(4),
    判定ＮＧコード７ binary(2),
    判定ＮＧコード７該当券 binary(4),
    判定ＮＧコード８ binary(2),
    判定ＮＧコード８該当券 binary(4),
    券エンコード情報１枚目情報 binary(288),
    券エンコード情報２枚目情報 binary(288),
    券エンコード情報３枚目情報 binary(288),
    券エンコード情報４枚目情報 binary(288)
  );
END;

IF object_id(N'${RiyoDataDatabaseName}.dbo.D_RIYO_DATA_W1_${Sta}') IS NULL
BEGIN
  CREATE TABLE ${RiyoDataDatabaseName}.dbo.D_RIYO_DATA_W1_${Sta}
  (
    UPDATE_DATE datetime NOT NULL,
    基本ヘッダーデータ種別 binary(1),
    基本ヘッダー駅コード binary(2) NOT NULL,
    基本ヘッダー処理日時 binary(7) NOT NULL,
    基本ヘッダーコーナー binary(1) NOT NULL,
    基本ヘッダー号機 binary(1) NOT NULL,
    基本ヘッダーシーケンスNo binary(4) NOT NULL,
    基本ヘッダーバージョン binary(1),
    通路方向 binary(1),
    判定結果 binary(2),
    発着情報乗車券発駅 binary(2),
    発着情報乗車券着駅 binary(2),
    発着情報特急券発駅 binary(2),
    発着情報特急券着駅 binary(2),
    発着情報のぞみ区間発駅 binary(2),
    発着情報のぞみ区間着駅 binary(2),
    発着情報グリーン区間発駅 binary(2),
    発着情報グリーン区間着駅 binary(2),
    発着情報FREX区間発駅 binary(2),
    発着情報FREX区間着駅 binary(2),
    入場駅情報乗車券入場駅 binary(2),
    入場駅情報特急券入場駅 binary(2),
    入場日時情報乗車券月日時分 binary(4),
    入場日時情報特急券月日時分 binary(4),
    当駅迄券情報乗車券乗車駅 binary(2),
    当駅迄券情報特急券乗車駅 binary(2),
    当駅から券情報乗車券着駅 binary(2),
    大小区分大人小児 binary(1),
    性別区分男性女性 binary(1),
    通用種別１枚目情報券種 binary(1),
    通用種別１枚目情報有効開始日 binary(4),
    通用種別１枚目情報有効終了日 binary(4),
    通用種別２枚目情報券種 binary(1),
    通用種別２枚目情報有効開始日 binary(4),
    通用種別２枚目情報有効終了日 binary(4),
    通用種別３枚目情報券種 binary(1),
    通用種別３枚目情報有効開始日 binary(4),
    通用種別３枚目情報有効終了日 binary(4),
    指定券情報指定１指定区間 binary(4),
    指定券情報指定１列車番号 binary(3),
    指定券情報指定１号車番号 binary(1),
    指定券情報指定１席番 binary(2),
    指定券情報指定２指定区間 binary(4),
    指定券情報指定２列車番号 binary(3),
    指定券情報指定２号車番号 binary(1),
    指定券情報指定２席番 binary(2),
    指定券情報指定３指定区間 binary(4),
    指定券情報指定３列車番号 binary(3),
    指定券情報指定３号車番号 binary(1),
    指定券情報指定３席番 binary(2),
    不正判定対象区分ビット binary(2),
    投入枚数 binary(1),
    併用パターン種別 binary(1),
    券読取情報１枚目情報区間 binary(4),
    券読取情報１枚目情報集計券種 binary(1),
    券読取情報１枚目情報割引 binary(1),
    券読取情報１枚目情報商品番号 binary(3),
    券読取情報１枚目情報発行会社 binary(2),
    券読取情報１枚目情報有効開始日 binary(4),
    券読取情報１枚目情報発行月日 binary(2),
    券読取情報２枚目情報区間 binary(4),
    券読取情報２枚目情報集計券種 binary(1),
    券読取情報２枚目情報割引 binary(1),
    券読取情報２枚目情報商品番号 binary(3),
    券読取情報２枚目情報発行会社 binary(2),
    券読取情報２枚目情報有効開始日 binary(4),
    券読取情報２枚目情報発行月日 binary(2),
    券読取情報３枚目情報区間 binary(4),
    券読取情報３枚目情報集計券種 binary(1),
    券読取情報３枚目情報割引 binary(1),
    券読取情報３枚目情報商品番号 binary(3),
    券読取情報３枚目情報発行会社 binary(2),
    券読取情報３枚目情報有効開始日 binary(4),
    券読取情報３枚目情報発行月日 binary(2),
    券読取情報４枚目情報区間 binary(4),
    券読取情報４枚目情報集計券種 binary(1),
    券読取情報４枚目情報割引 binary(1),
    券読取情報４枚目情報商品番号 binary(3),
    券読取情報４枚目情報発行会社 binary(2),
    券読取情報４枚目情報有効開始日 binary(4),
    券読取情報４枚目情報発行月日 binary(2),
    券読取情報１枚目情報当駅有効 binary(1),
    券読取情報２枚目情報当駅有効 binary(1),
    券読取情報３枚目情報当駅有効 binary(1),
    券読取情報４枚目情報当駅有効 binary(1),
    ＳＦ引去り金額 binary(4),
    ＳＦ利用区間１・利用駅１ binary(2),
    ＳＦ利用区間１・利用駅２ binary(2),
    ＳＦ利用区間２・利用駅１ binary(2),
    ＳＦ利用区間２・利用駅２ binary(2),
    乗車始点駅 binary(2),
    券通しマスタ適用有無 binary(1),
    新幹線IC利用 binary(1),
    予備１ binary(45),
    サム値 binary(2),
    未使用 binary(52),
    券エンコード情報１枚目情報 binary(288),
    券エンコード情報２枚目情報 binary(288),
    券エンコード情報３枚目情報 binary(288),
    券エンコード情報４枚目情報 binary(288)
  );
  ALTER TABLE ${RiyoDataDatabaseName}.dbo.D_RIYO_DATA_W1_${Sta}
  ADD CONSTRAINT pk_D_RIYO_DATA_W1_${Sta} PRIMARY KEY (基本ヘッダー処理日時,基本ヘッダー駅コード,基本ヘッダーコーナー,基本ヘッダー号機,基本ヘッダーシーケンスNo);
  CREATE INDEX idx_D_RIYO_DATA_W1_${Sta} ON ${RiyoDataDatabaseName}.dbo.D_RIYO_DATA_W1_${Sta}(UPDATE_DATE);
END;

IF object_id(N'D_RIYO_DATA_W1_TEMP_${Sta}') IS NULL
BEGIN
  CREATE TABLE D_RIYO_DATA_W1_TEMP_${Sta}
  (
    基本ヘッダーデータ種別 binary(1),
    基本ヘッダー駅コード binary(2) NOT NULL,
    基本ヘッダー処理日時 binary(7) NOT NULL,
    基本ヘッダーコーナー binary(1) NOT NULL,
    基本ヘッダー号機 binary(1) NOT NULL,
    基本ヘッダーシーケンスNo binary(4) NOT NULL,
    基本ヘッダーバージョン binary(1),
    通路方向 binary(1),
    判定結果 binary(2),
    発着情報乗車券発駅 binary(2),
    発着情報乗車券着駅 binary(2),
    発着情報特急券発駅 binary(2),
    発着情報特急券着駅 binary(2),
    発着情報のぞみ区間発駅 binary(2),
    発着情報のぞみ区間着駅 binary(2),
    発着情報グリーン区間発駅 binary(2),
    発着情報グリーン区間着駅 binary(2),
    発着情報FREX区間発駅 binary(2),
    発着情報FREX区間着駅 binary(2),
    入場駅情報乗車券入場駅 binary(2),
    入場駅情報特急券入場駅 binary(2),
    入場日時情報乗車券月日時分 binary(4),
    入場日時情報特急券月日時分 binary(4),
    当駅迄券情報乗車券乗車駅 binary(2),
    当駅迄券情報特急券乗車駅 binary(2),
    当駅から券情報乗車券着駅 binary(2),
    大小区分大人小児 binary(1),
    性別区分男性女性 binary(1),
    通用種別１枚目情報券種 binary(1),
    通用種別１枚目情報有効開始日 binary(4),
    通用種別１枚目情報有効終了日 binary(4),
    通用種別２枚目情報券種 binary(1),
    通用種別２枚目情報有効開始日 binary(4),
    通用種別２枚目情報有効終了日 binary(4),
    通用種別３枚目情報券種 binary(1),
    通用種別３枚目情報有効開始日 binary(4),
    通用種別３枚目情報有効終了日 binary(4),
    指定券情報指定１指定区間 binary(4),
    指定券情報指定１列車番号 binary(3),
    指定券情報指定１号車番号 binary(1),
    指定券情報指定１席番 binary(2),
    指定券情報指定２指定区間 binary(4),
    指定券情報指定２列車番号 binary(3),
    指定券情報指定２号車番号 binary(1),
    指定券情報指定２席番 binary(2),
    指定券情報指定３指定区間 binary(4),
    指定券情報指定３列車番号 binary(3),
    指定券情報指定３号車番号 binary(1),
    指定券情報指定３席番 binary(2),
    不正判定対象区分ビット binary(2),
    投入枚数 binary(1),
    併用パターン種別 binary(1),
    券読取情報１枚目情報区間 binary(4),
    券読取情報１枚目情報集計券種 binary(1),
    券読取情報１枚目情報割引 binary(1),
    券読取情報１枚目情報商品番号 binary(3),
    券読取情報１枚目情報発行会社 binary(2),
    券読取情報１枚目情報有効開始日 binary(4),
    券読取情報１枚目情報発行月日 binary(2),
    券読取情報２枚目情報区間 binary(4),
    券読取情報２枚目情報集計券種 binary(1),
    券読取情報２枚目情報割引 binary(1),
    券読取情報２枚目情報商品番号 binary(3),
    券読取情報２枚目情報発行会社 binary(2),
    券読取情報２枚目情報有効開始日 binary(4),
    券読取情報２枚目情報発行月日 binary(2),
    券読取情報３枚目情報区間 binary(4),
    券読取情報３枚目情報集計券種 binary(1),
    券読取情報３枚目情報割引 binary(1),
    券読取情報３枚目情報商品番号 binary(3),
    券読取情報３枚目情報発行会社 binary(2),
    券読取情報３枚目情報有効開始日 binary(4),
    券読取情報３枚目情報発行月日 binary(2),
    券読取情報４枚目情報区間 binary(4),
    券読取情報４枚目情報集計券種 binary(1),
    券読取情報４枚目情報割引 binary(1),
    券読取情報４枚目情報商品番号 binary(3),
    券読取情報４枚目情報発行会社 binary(2),
    券読取情報４枚目情報有効開始日 binary(4),
    券読取情報４枚目情報発行月日 binary(2),
    券読取情報１枚目情報当駅有効 binary(1),
    券読取情報２枚目情報当駅有効 binary(1),
    券読取情報３枚目情報当駅有効 binary(1),
    券読取情報４枚目情報当駅有効 binary(1),
    ＳＦ引去り金額 binary(4),
    ＳＦ利用区間１・利用駅１ binary(2),
    ＳＦ利用区間１・利用駅２ binary(2),
    ＳＦ利用区間２・利用駅１ binary(2),
    ＳＦ利用区間２・利用駅２ binary(2),
    乗車始点駅 binary(2),
    券通しマスタ適用有無 binary(1),
    新幹線IC利用 binary(1),
    予備１ binary(45),
    サム値 binary(2),
    未使用 binary(52),
    券エンコード情報１枚目情報 binary(288),
    券エンコード情報２枚目情報 binary(288),
    券エンコード情報３枚目情報 binary(288),
    券エンコード情報４枚目情報 binary(288)
  );
END;

IF object_id(N'${ShiteiDataDatabaseName}.dbo.D_SHITEI_DATA_${Sta}') IS NULL
BEGIN
  CREATE TABLE ${ShiteiDataDatabaseName}.dbo.D_SHITEI_DATA_${Sta}
  (
    UPDATE_DATE datetime NOT NULL,
    GICA_GET_STATUS tinyint,
    基本ヘッダー処理日時 binary(7),
    基本ヘッダー駅コード binary(2),
    基本ヘッダーコーナー binary(1),
    基本ヘッダー号機 binary(1),
    基本ヘッダーシーケンスNo binary(4),
    指定券情報指定１指定区間 binary(4),
    指定券情報指定１列車番号 binary(2),
    指定券情報指定１号車番号 binary(1),
    指定券情報指定１席番 binary(1),
    指定券情報指定１割引1 binary(1),
    指定券情報指定１割引2 binary(1),
    指定券情報指定１集計券種 binary(1),
    指定券情報指定２指定区間 binary(4),
    指定券情報指定２列車番号 binary(2),
    指定券情報指定２号車番号 binary(1),
    指定券情報指定２席番 binary(1),
    指定券情報指定２割引1 binary(1),
    指定券情報指定２割引2 binary(1),
    指定券情報指定２集計券種 binary(1),
    指定券情報指定３指定区間 binary(4),
    指定券情報指定３列車番号 binary(2),
    指定券情報指定３号車番号 binary(1),
    指定券情報指定３席番 binary(1),
    指定券情報指定３割引1 binary(1),
    指定券情報指定３割引2 binary(1),
    指定券情報指定３集計券種 binary(1),
    大小 binary(1)
  );
  CREATE CLUSTERED INDEX idx_D_SHITEI_DATA_${Sta} ON ${ShiteiDataDatabaseName}.dbo.D_SHITEI_DATA_${Sta}(UPDATE_DATE);
END;
