DROP TABLE D_BESSHU_DATA;
CREATE TABLE D_BESSHU_DATA
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    RAIL_SECTION_CODE varchar(3) NOT NULL,
    STATION_ORDER_CODE varchar(3) NOT NULL,
    CORNER_CODE int NOT NULL,
    UNIT_NO int NOT NULL,
    PASSAGE_DIRECTION int NOT NULL,
    PROCESSING_TIME varchar(14) NOT NULL,
    TICKET_CNT int NOT NULL,
    TICKET_NO int,
    DEPARTURE_STATION varchar(8),
    ARRIVAL_STATION varchar(8),
    RETURN_FLG varchar(1),
    CAUSE_FLG varchar(1)
);

ALTER TABLE D_BESSHU_DATA
ADD CONSTRAINT pk_D_BESSHU_DATA PRIMARY KEY ( RAIL_SECTION_CODE,STATION_ORDER_CODE,CORNER_CODE,UNIT_NO,PASSAGE_DIRECTION,PROCESSING_TIME,TICKET_CNT);

CREATE INDEX idx_D_BESSHU_DATA ON D_BESSHU_DATA(UPDATE_DATE);




