USE [EXOPMG]
GO
/****** Object:  Table [dbo].[D_CON_STATUS]    Script Date: 03/18/2019 15:18:35 ******/
DROP TABLE [dbo].[D_CON_STATUS]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[D_CON_STATUS](
    [INSERT_DATE] [datetime] NULL,
    [INSERT_USER_ID] [varchar](10) NULL,
    [INSERT_MACHINE_ID] [varchar](10) NULL,
    [UPDATE_DATE] [datetime] NULL,
    [UPDATE_USER_ID] [varchar](10) NULL,
    [UPDATE_MACHINE_ID] [varchar](10) NULL,
    [RAIL_SECTION_CODE] [varchar](3) NOT NULL,
    [STATION_ORDER_CODE] [varchar](3) NOT NULL,
    [CORNER_CODE] [int] NOT NULL,
    [UNIT_NO] [int] NOT NULL,
    [MODEL_CODE] [varchar](1) NOT NULL,
    [SYUSYU_DATE] [datetime] NOT NULL,
    [KAIDENGEN] [int] NULL,
    [KANSICONNECT] [int] NULL,
    [SHUSECONNECT] [int] NULL,
    [HAISINSYUCONNECT] [int] NULL,
    [HAISINICMCONNECT] [int] NULL,
    [EXTOKATUCONNECT] [int] NULL,
    [EXTOKATUDLCONNECT] [int] NULL,
    [IDCENTERCONNECT] [int] NULL,
    [IDNINSYOCONNECT] [int] NULL,
    [HAISINSYUCONNECTQR] [int] NULL,
    [HAISINICMCONNECTQR] [int] NULL,
 CONSTRAINT [pk_D_CON_STATUS] PRIMARY KEY CLUSTERED 
(
    [RAIL_SECTION_CODE] ASC,
    [STATION_ORDER_CODE] ASC,
    [CORNER_CODE] ASC,
    [UNIT_NO] ASC,
    [MODEL_CODE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [idx_D_CON_STATUS] ON [dbo].[D_CON_STATUS] 
(
    [SYUSYU_DATE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
