DROP TABLE D_CON_STATUS;
CREATE TABLE D_CON_STATUS
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    RAIL_SECTION_CODE varchar(3) NOT NULL,
    STATION_ORDER_CODE varchar(3) NOT NULL,
    CORNER_CODE int NOT NULL,
    UNIT_NO int NOT NULL,
    MODEL_CODE varchar(1) NOT NULL,
    SYUSYU_DATE datetime NOT NULL,
    KAIDENGEN int,
    KANSICONNECT int,
    SHUSECONNECT int,
    HAISINSYUCONNECT int,
    HAISINICMCONNECT int,
    EXTOKATUCONNECT int,
    EXTOKATUDLCONNECT int,
    IDCENTERCONNECT int
);

ALTER TABLE D_CON_STATUS
ADD CONSTRAINT pk_D_CON_STATUS PRIMARY KEY ( RAIL_SECTION_CODE,STATION_ORDER_CODE,CORNER_CODE,UNIT_NO,MODEL_CODE);

CREATE INDEX idx_D_CON_STATUS ON D_CON_STATUS(SYUSYU_DATE);




