DROP TABLE D_FAULT_DATA;
CREATE TABLE D_FAULT_DATA
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    RAIL_SECTION_CODE varchar(3) NOT NULL,
    STATION_ORDER_CODE varchar(3) NOT NULL,
    CORNER_CODE int NOT NULL,
    MODEL_CODE varchar(1) NOT NULL,
    UNIT_NO int NOT NULL,
    OCCUR_DATE varchar(14) NOT NULL,
    PASSAGE_DIRECTION int NOT NULL,
    ERROR_TYPE varchar(1) NOT NULL,
    ACT_STEP varchar(1) NOT NULL,
    ERR_CODE varchar(6) NOT NULL,
    ERR_ITEM varchar(40),
    ERROR_KIND varchar(12),
    DTL_INFO varchar(540),
    RES_INFO varchar(150)
);

ALTER TABLE D_FAULT_DATA
ADD CONSTRAINT pk_D_FAULT_DATA PRIMARY KEY ( RAIL_SECTION_CODE,STATION_ORDER_CODE,CORNER_CODE,MODEL_CODE,UNIT_NO,OCCUR_DATE,PASSAGE_DIRECTION,ERROR_TYPE,ACT_STEP,ERR_CODE);

CREATE INDEX idx_D_FAULT_DATA ON D_FAULT_DATA(UPDATE_DATE);




