DROP TABLE D_FUNSHITSU_DATA;
CREATE TABLE D_FUNSHITSU_DATA
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    RAIL_SECTION_CODE varchar(3) NOT NULL,
    STATION_ORDER_CODE varchar(3) NOT NULL,
    CORNER_CODE int NOT NULL,
    PROCESSING_TIME varchar(14) NOT NULL,
    UNIT_NO int NOT NULL,
    PASSAGE_DIRECTION int NOT NULL,
    TICKET_NO int NOT NULL,
    RAIL_CODE int,
    ID_NO varchar(16) NOT NULL
);

ALTER TABLE D_FUNSHITSU_DATA
ADD CONSTRAINT pk_D_FUNSHITSU_DATA PRIMARY KEY ( RAIL_SECTION_CODE,STATION_ORDER_CODE,CORNER_CODE,PROCESSING_TIME,UNIT_NO,PASSAGE_DIRECTION,TICKET_NO);

CREATE INDEX idx_D_FUNSHITSU_DATA ON D_FUNSHITSU_DATA(UPDATE_DATE);




