DROP TABLE D_FUSEI_JOSHA_DATA;
CREATE TABLE D_FUSEI_JOSHA_DATA
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    RAIL_SECTION_CODE varchar(3) NOT NULL,
    STATION_ORDER_CODE varchar(3) NOT NULL,
    CORNER_CODE int NOT NULL,
    UNIT_NO int NOT NULL,
    PASSAGE_DIRECTION int NOT NULL,
    PROCESSING_TIME varchar(14) NOT NULL,
    WRANG_TARGET_NO int NOT NULL
);

ALTER TABLE D_FUSEI_JOSHA_DATA
ADD CONSTRAINT pk_D_FUSEI_JOSHA_DATA PRIMARY KEY ( RAIL_SECTION_CODE,STATION_ORDER_CODE,CORNER_CODE,UNIT_NO,PASSAGE_DIRECTION,PROCESSING_TIME,WRANG_TARGET_NO);

CREATE INDEX idx_D_FUSEI_JOSHA_DATA ON D_FUSEI_JOSHA_DATA(UPDATE_DATE);




