DROP TABLE D_TRAFFIC_DATA;
CREATE TABLE D_TRAFFIC_DATA
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    RAIL_SECTION_CODE varchar(3) NOT NULL,
    STATION_ORDER_CODE varchar(3) NOT NULL,
    CORNER_CODE int NOT NULL,
    DATE varchar(14) NOT NULL,
    TIME_ZONE varchar(14) NOT NULL,
    TICKET_NO int NOT NULL,
    STATION_IN bigint,
    STATION_OUT bigint,
    STATION_SUM bigint
);

ALTER TABLE D_TRAFFIC_DATA
ADD CONSTRAINT pk_D_TRAFFIC_DATA PRIMARY KEY ( RAIL_SECTION_CODE,STATION_ORDER_CODE,CORNER_CODE,DATE,TIME_ZONE,TICKET_NO);

CREATE INDEX idx_D_TRAFFIC_DATA ON D_TRAFFIC_DATA(UPDATE_DATE);




