DROP TABLE M_BRANCH_OFFICE;
CREATE TABLE M_BRANCH_OFFICE
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    GROUP_NO int NOT NULL,
    CODE varchar(3) NOT NULL,
    NAME varchar(40)
);

ALTER TABLE M_BRANCH_OFFICE
ADD CONSTRAINT pk_M_BRANCH_OFFICE PRIMARY KEY ( GROUP_NO,CODE);





