DROP TABLE M_ISSUE_ORGANIZE;
CREATE TABLE M_ISSUE_ORGANIZE
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    ORGANIZE_NO int NOT NULL,
    ORGANIZE_NAME varchar(30)
);

ALTER TABLE M_ISSUE_ORGANIZE
ADD CONSTRAINT pk_M_ISSUE_ORGANIZE PRIMARY KEY ( ORGANIZE_NO);





