DROP TABLE M_KADOHOSYU_FIELD;
CREATE TABLE M_KADOHOSYU_FIELD
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    GROUP_NO int NOT NULL,
    MODEL_CODE varchar(1) NOT NULL,
    DATA_SYUBETU int NOT NULL,
    KOMOKU_NO int NOT NULL,
    KAI_FLD varchar(20),
    SYU_FLD varchar(20),
    GOU_FLD varchar(20)
);

ALTER TABLE M_KADOHOSYU_FIELD
ADD CONSTRAINT pk_M_KADOHOSYU_FIELD PRIMARY KEY ( GROUP_NO,MODEL_CODE,DATA_SYUBETU,KOMOKU_NO);





