DROP TABLE M_MACHINE_DATA_VER;
CREATE TABLE M_MACHINE_DATA_VER
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    VERSION varchar(3) NOT NULL
);

ALTER TABLE M_MACHINE_DATA_VER
ADD CONSTRAINT pk_M_MACHINE_DATA_VER PRIMARY KEY ( VERSION);





