DROP TABLE M_MACHINE;
CREATE TABLE M_MACHINE
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    SETTING_START_DATE varchar(8) NOT NULL,
    SETTING_END_DATE varchar(8) NOT NULL,
    BRANCH_OFFICE_CODE varchar(3) NOT NULL,
    MONITOR_STATION_NAME varchar(40),
    MONITOR_RAIL_SECTION_CODE varchar(3) NOT NULL,
    MONITOR_STATION_ORDER_CODE varchar(3) NOT NULL,
    STATION_NAME varchar(40),
    RAIL_SECTION_CODE varchar(3) NOT NULL,
    STATION_ORDER_CODE varchar(3) NOT NULL,
    CORNER_NAME varchar(40),
    CORNER_CODE int NOT NULL,
    MODEL_NAME varchar(40),
    MODEL_CODE varchar(2) NOT NULL,
    UNIT_NO int NOT NULL,
    ADDRESS varchar(15) NOT NULL,
    SUBNET_MASK varchar(15),
    DEFAULT_GW varchar(15),
    MONITOR_MODEL_NAME varchar(15),
    MONITOR_ADDRESS varchar(15) NOT NULL,
    Y_AREA_CODE int,
    G_AREA_CODE int,
    W_AREA_CODE int,
    NK_PORT_NO int NOT NULL
);

ALTER TABLE M_MACHINE
ADD CONSTRAINT pk_M_MACHINE PRIMARY KEY ( SETTING_START_DATE,BRANCH_OFFICE_CODE,RAIL_SECTION_CODE,STATION_ORDER_CODE,CORNER_CODE,MODEL_CODE,UNIT_NO);

CREATE INDEX idx_M_MACHINE ON M_MACHINE(ADDRESS);




