DROP TABLE M_NOTIFIABLE_ERR_CODE;
CREATE TABLE M_NOTIFIABLE_ERR_CODE
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    RAIL_SECTION_CODE varchar(3) NOT NULL,
    STATION_ORDER_CODE varchar(3) NOT NULL,
    MODEL_CODE varchar(1) NOT NULL,
    ERR_CODE varchar(6) NOT NULL,
    SNMP_SEVERITY varchar(8) NOT NULL
);

ALTER TABLE M_NOTIFIABLE_ERR_CODE
ADD CONSTRAINT pk_M_NOTIFIABLE_ERR_CODE PRIMARY KEY ( RAIL_SECTION_CODE,STATION_ORDER_CODE,MODEL_CODE,ERR_CODE);





