DROP TABLE M_PATTERN_DATA;
CREATE TABLE M_PATTERN_DATA
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    MODEL_CODE varchar(2) NOT NULL,
    MST_KIND varchar(3) NOT NULL,
    PATTERN_NO varchar(2) NOT NULL,
    PATTERN_NAME varchar(20)
);

ALTER TABLE M_PATTERN_DATA
ADD CONSTRAINT pk_M_PATTERN_DATA PRIMARY KEY ( MODEL_CODE,MST_KIND,PATTERN_NO);





