DROP TABLE M_PRG_DL_DELIVERY_STS_NAME;
CREATE TABLE M_PRG_DL_DELIVERY_STS_NAME
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    MODEL_CODE varchar(1) NOT NULL,
    FILE_KBN varchar(3) NOT NULL,
    STS int NOT NULL,
    STS_NAME varchar(10)
);

ALTER TABLE M_PRG_DL_DELIVERY_STS_NAME
ADD CONSTRAINT pk_M_PRG_DL_DELIVERY_STS_NAME PRIMARY KEY ( MODEL_CODE,FILE_KBN,STS);





