DROP TABLE M_THROUGH_GATE;
CREATE TABLE M_THROUGH_GATE
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    ERROR_NO int NOT NULL,
    ERROR_NAME varchar(150)
);

ALTER TABLE M_THROUGH_GATE
ADD CONSTRAINT pk_M_THROUGH_GATE PRIMARY KEY ( ERROR_NO);





