DROP TABLE M_WARN_TICKET;
CREATE TABLE M_WARN_TICKET
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    WRANG_TARGET_NO int NOT NULL,
    WRANG_TARGET_NAME varchar(60)
);

ALTER TABLE M_WARN_TICKET
ADD CONSTRAINT pk_M_WARN_TICKET PRIMARY KEY ( WRANG_TARGET_NO);





