DROP TABLE S_MST_VER_INFO_EXPECTED;
CREATE TABLE S_MST_VER_INFO_EXPECTED
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    MODEL_CODE varchar(1) NOT NULL,
    RAIL_SECTION_CODE varchar(3) NOT NULL,
    STATION_ORDER_CODE varchar(3) NOT NULL,
    CORNER_CODE int NOT NULL,
    UNIT_NO int NOT NULL,
    DATA_KIND varchar(3) NOT NULL,
    DATA_SUB_KIND varchar(2) NOT NULL,
    DATA_VERSION varchar(8)
);

ALTER TABLE S_MST_VER_INFO_EXPECTED
ADD CONSTRAINT pk_S_MST_VER_INFO_EXPECTED PRIMARY KEY ( MODEL_CODE,RAIL_SECTION_CODE,STATION_ORDER_CODE,CORNER_CODE,UNIT_NO,DATA_KIND);





