DROP TABLE S_MST_DATA_HEADLINE;
CREATE TABLE S_MST_DATA_HEADLINE
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    MODEL_CODE varchar(2) NOT NULL,
    DATA_KIND varchar(3) NOT NULL,
    DATA_SUB_KIND varchar(2) NOT NULL,
    DATA_VERSION varchar(8) NOT NULL,
    FILE_NAME varchar(80),
    HASH_VALUE varchar(32)
);

ALTER TABLE S_MST_DATA_HEADLINE
ADD CONSTRAINT pk_S_MST_DATA_HEADLINE PRIMARY KEY ( MODEL_CODE,DATA_KIND,DATA_SUB_KIND,DATA_VERSION);





