DROP TABLE S_PRG_DLL_VER;
CREATE TABLE S_PRG_DLL_VER
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    MODEL_CODE varchar(1) NOT NULL,
    DATA_KIND varchar(3) NOT NULL,
    DATA_SUB_KIND varchar(2) NOT NULL,
    RAIL_SECTION_CODE varchar(3) NOT NULL,
    STATION_ORDER_CODE varchar(3) NOT NULL,
    CORNER_CODE int NOT NULL,
    UNIT_NO int NOT NULL,
    DATA_VERSION varchar(8) NOT NULL,
    UNCERTAIN_FLG varchar(1)
);

ALTER TABLE S_PRG_DLL_VER
ADD CONSTRAINT pk_S_PRG_DLL_VER PRIMARY KEY ( MODEL_CODE,DATA_KIND,DATA_SUB_KIND,RAIL_SECTION_CODE,STATION_ORDER_CODE,CORNER_CODE,UNIT_NO);





