DROP TABLE S_PRG_LIST_HEADLINE;
CREATE TABLE S_PRG_LIST_HEADLINE
(
    INSERT_DATE datetime,
    INSERT_USER_ID varchar(10),
    INSERT_MACHINE_ID varchar(10),
    UPDATE_DATE datetime,
    UPDATE_USER_ID varchar(10),
    UPDATE_MACHINE_ID varchar(10),
    MODEL_CODE varchar(2) NOT NULL,
    DATA_KIND varchar(3) NOT NULL,
    DATA_SUB_KIND varchar(2) NOT NULL,
    DATA_VERSION varchar(8) NOT NULL,
    LIST_VERSION varchar(2) NOT NULL,
    FILE_NAME varchar(80),
    HASH_VALUE varchar(32),
    FILE_CREATE_DATE
 varchar(8)
);

ALTER TABLE S_PRG_LIST_HEADLINE
ADD CONSTRAINT pk_S_PRG_LIST_HEADLINE PRIMARY KEY ( MODEL_CODE,DATA_KIND,DATA_SUB_KIND,DATA_VERSION,LIST_VERSION);





